language: ruby

rvm: # the Ruby versions to be used
  - 2.0.0

env:
  - REMOTE=false
  - REMOTE=true

branches:
  only:
    - dev

before_install:
  - sudo apt-get install openjdk-7-jdk
  - java -version
  - mvn -version

before_script:
  - rake jekyll
  
script:
  - echo test

after_success:
  - rake deploy

notifications:
  email:
    - vera_kruhliakova@epam.com
