language: ruby

rvm: # the Ruby versions to be used
  - 2.0.0

before_install:
  - sudo apt-get install openjdk-6-jdk
  - java -version
  - gem update
  - gem install jekyll
  - gem install selenium-webdriver
  - gem install cucumber
  - gem install rspec
  - gem install capybara
  - gem install poltergeist
  - phantomjs --version

before_script:
  - rake local
  
script:
  - rake test

notifications:
  email:
    - vera_kruhliakova@epam.com