language: ruby

rvm: # the Ruby versions to be used
  - 2.0.0

before_install:
  - gem update
  - gem install jekyll
  - gem install selenium-webdriver
  - phantomjs --version

before_script:
  - rake jekyll
  
script:
  - rake
